/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pieface;

import java.io.IOException;
import java.rmi.server.ExportException;
import java.util.Set;

import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okio.Buffer;
import org.junit.Before;
import org.openqa.selenium.By;
import org.openqa.selenium.Cookie;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class LibraryTest {

    private WebDriver webDriver;

    @BeforeClass
    public static void setupWebDriver() {
        System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + "/src/test/resources/chromedriver");
        System.out.println(System.getProperties());
    }

    @Before
    public void setup() {
        webDriver = new ChromeDriver();
    }

    @Test public void openPieFace() throws IOException {
        System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + "/src/test/resources/chromedriver");
        webDriver = new ChromeDriver();
        webDriver.get("http://logbook.pieface.com.au/");
        webDriver.findElement(By.xpath("//*[@id=\"navbarCollapse\"]/div[2]/a")).click();
        webDriver.findElement(By.id("Input_ExternalId")).sendKeys("3389");
        webDriver.findElement(By.id("Input_Password")).sendKeys("3389");
        webDriver.findElement(By.xpath("//*[@id=\"account\"]/div[5]/button")).click();
        System.out.println(webDriver.manage().getCookies());
        OkHttpClient client = Client.getUnsafeOkHttpClient();
        MediaType mediaType = MediaType.parse("application/json");
        RequestBody body = RequestBody.create(mediaType, "{\n    \"taskId\": 28,\n    \"performedBy\": \"Ramesh\",\n    \"enteredDate\": \"2021-10-17\",\n    \"enteredTime\": \"16:30\",\n    \"addProperty1\": \"Cleaned\",\n    \"addProperty2\": \"Cleaned\",\n    \"addProperty3\": null\n}");
        Request request = new Request.Builder()
            .url("https://logbook.pieface.com.au/api/task/record?timeZone=Australia/Melbourne")
            .method("POST", body)
            .addHeader("Content-Type", "application/json")
            .addHeader("Cookie", webDriver.manage().getCookies().toString())
            .build();
//        Response response = client.newCall(request).execute();
//        System.out.println(response.body().string());
    }
}
